// <auto-generated />
namespace RealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _2121eqwd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_2121eqwd));
        
        string IMigrationMetadata.Id
        {
            get { return "201903020415459_2121eqwd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
