// <auto-generated />
namespace RealEstate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class efsb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(efsb));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280902010_efsb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
